name: kubectl Action
description: Deploy to a Kubernetes cluster
author: Statistics Canada

branding:
  color: 'purple'
  icon: 'upload-cloud'

runs:
  using: docker
  image: Dockerfile

inputs:
  app:
    description: 'application to run'
    default: 'kubectl'
  args:
    description: 'arguments to pass to kubectl'
  dir:
    description: 'The directory to execute the command under'
    default: '.'
  kubeconfig:
    description: 'base64 encoded .kube/config'
