name: Helm gh-pages Action
description: Publishes the Helm chart into gh-pages
author: Statistics Canada

branding:
  color: 'purple'
  icon: 'upload-cloud'

runs:
  using: docker
  image: Dockerfile
